uploaded metadata
fontsKscVxiCiwUWVsFWFA3Bjnkf6ByYO6CLYdB4HQEYWoff2
	^ WAFileLibraryResource
		filepath: 'fonts/KscVxiCiwUWVsFWFA3Bjnkf6ByYO6CLYdB4HQEY.woff2'
		mimeType: (WAMimeType main: 'application' sub: 'octet-stream')
		cacheDuration: (Duration days: 0 hours: 0 minutes: 30 seconds: 0)
		contents: (GRDelayedSend receiver: self selector: #fontsKscVxiCiwUWVsFWFA3Bjnkf6ByYO6CLYdB4HQEYWoff2Content)