uploaded metadata
fontsoMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0AWoff2
	^ WAFileLibraryResource
		filepath: 'fonts/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2'
		mimeType: (WAMimeType main: 'application' sub: 'octet-stream')
		cacheDuration: (Duration days: 0 hours: 0 minutes: 30 seconds: 0)
		contents: (GRDelayedSend receiver: self selector: #fontsoMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0AWoff2Content)