uploaded metadata
fontsuYECMKoHcO9x1wdmbyHIm3kf6ByYO6CLYdB4HQEYWoff2
	^ WAFileLibraryResource
		filepath: 'fonts/uYECMKoHcO9x1wdmbyHIm3kf6ByYO6CLYdB4HQEY.woff2'
		mimeType: (WAMimeType main: 'application' sub: 'octet-stream')
		cacheDuration: (Duration days: 0 hours: 0 minutes: 30 seconds: 0)
		contents: (GRDelayedSend receiver: self selector: #fontsuYECMKoHcO9x1wdmbyHIm3kf6ByYO6CLYdB4HQEYWoff2Content)