hooks
style
	^ '.demo-container {
        height: 500px;
        margin: 0px;
        font-size: 16px;
        overflow: scroll;
      }

      .demo-header-toolbar {
        z-index: 10;
      }

      .hero .catalog-toolbar-container {
        width: 480px;
        height: 72px;
      }

      .hero .catalog-toolbar-container .mdc-toolbar {
        box-shadow:
          0px 2px 4px -1px rgba(0, 0, 0, 0.2),
          0px 4px 5px 0px rgba(0, 0, 0, 0.14),
          0px 1px 10px 0px rgba(0, 0, 0, 0.12);
      }

      .examples {
        display: block;
      }

      .example {
        display: inline-block;
        width: 320px;
        height: 600px;
        margin: 24px;
      }

      .example iframe {
        border: 1px solid #eee;
      }

      .examples h2 {
        font-size: 24px;
        margin-bottom: 16px;
      }

      div.intro {
        padding: 48px 24px;
      }'